# Generated by Django 5.2.3 on 2025-07-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('conference', 'Conference'), ('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('office', 'Office')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
            ],
        ),
    ]
