# Generated by Django 5.2.3 on 2025-07-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_building_room_room_name_remove_room_floor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='building_name',
            new_name='buildingName',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='floor_name',
            new_name='floorName',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='roomNumber',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='roomType',
        ),
    ]
