# Generated by Django 5.2.3 on 2025-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_content_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Binary image data stored in database', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
    ]
