# Generated by Django 5.2.3 on 2025-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fix_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable notifications and sounds for this user'),
        ),
    ]
