# Generated by Django 5.2.3 on 2025-07-08 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_room_amenities_remove_room_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemReport',
            new_name='ReportProblem',
        ),
    ]
