# Generated by Django 5.2.3 on 2025-07-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_problemreport_reportproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
    ]
