# Generated by Django 5.2.3 on 2025-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for SMS verification", max_length=15, null=True),
        ),
    ]
