# Generated by Django 5.2.3 on 2025-07-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True),
        ),
    ]
