# Generated by Django 5.2 on 2025-07-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the room is available for booking'),
        ),
    ]
