# Generated by Django 5.2 on 2025-08-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_reportproblem_admin_reply_reportproblem_admin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportproblem',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='reportproblem',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='reportproblem',
            name='reply_date',
        ),
        migrations.RemoveField(
            model_name='reportproblem',
            name='updated_at',
        ),
    ]
